export const RealtimeEvents = {
  MessageCreate: 'message:create',
  MessageCreated: 'message:created',
  MessageUpdate: 'message:update',
  MessageUpdated: 'message:updated',
  MessageDelete: 'message:delete',
  MessageDeleted: 'message:deleted',
  ThreadJoin: 'thread:join',
  ThreadMessageCreate: 'thread:message:create',
  ThreadMessageCreated: 'thread:message:created',
  ThreadMessageUpdated: 'thread:message:updated',
  ThreadMessageDeleted: 'thread:message:deleted',
  ConversationJoin: 'conversation:join',
  DmCreated: 'dm:created',
  DmUnread: 'dm:unread',
  FriendRequest: 'friend:request',
  FriendUpdated: 'friend:updated',
  NotificationCreated: 'notification:created',
  NotificationUnread: 'notification:unread',
  ChannelJoin: 'channel:join',
  ChannelLeave: 'channel:leave',
  TypingStart: 'typing:start',
  TypingStop: 'typing:stop',
  PresenceUpdate: 'presence:update',
  ReactionToggle: 'reaction:toggle',
  ReactionUpdated: 'reaction:updated',
  VoiceJoin: 'voice:join',
  VoiceLeave: 'voice:leave',
  VoiceState: 'voice:state',
  VoiceUserJoined: 'voice:user-joined',
  VoiceUserUpdated: 'voice:user-updated',
  VoiceUserLeft: 'voice:user-left',
  VoiceActive: 'voice:active',
  VoiceEnded: 'voice:ended',
  WebRtcOffer: 'webrtc:offer',
  WebRtcAnswer: 'webrtc:answer',
  WebRtcIceCandidate: 'webrtc:ice-candidate',
} as const;

export type RealtimeEvent = (typeof RealtimeEvents)[keyof typeof RealtimeEvents];
